_all:
  version:
    link: 'https://www.npmjs.com/package/{{{fullname}}}'
    img: 'https://img.shields.io/npm/v/{{{fullname}}}.svg'
    alt: '{{{fullname}}} on NPM'
  license:
    link: 'https://opensource.org/licenses/MIT'
    img: 'https://img.shields.io/npm/l/{{{fullname}}}.svg?label=License'
    alt: 'License: MIT'
  deepscan:
    link: 'https://deepscan.io/dashboard#view=project&tid=2114&pid=2993&bid=23256'
    img: 'https://deepscan.io/api/teams/2114/projects/2993/branches/23256/badge/grade.svg'
    alt: 'Code quality on DeepScan'
  issues:
    link: 'https://github.com/freesewing/freesewing/issues?q=is%3Aissue+is%3Aopen+label%3Apkg%3A{{name}}'
    img: 'https://img.shields.io/github/issues/freesewing/freesewing/pkg:{{name}}.svg?label=Issues'
    alt: 'Open issues tagged pkg:{{name}}'
  contributors:
    link: '#contributors-'
    img: 'https://img.shields.io/badge/all_contributors-{{ name }}-pink.svg'
    alt: 'All Contributors'
_social:
  twitter:
    link: 'https://twitter.com/freesewing_org'
    img: 'https://img.shields.io/badge/%F3%A0%80%A0-Follow%20us-blue.svg?logo=twitter&logoColor=white&logoWidth=15'
    alt: 'Follow @freesewing_org on Twitter'
  discord:
    link: 'https://chat.freesewing.org'
    img: 'https://img.shields.io/discord/698854858052075530?label=Chat%20on%20Discord'
    alt: 'Chat with us on Discord'
  patron:
    link: 'https://freesewing.org/patrons/join'
    img: 'https://img.shields.io/badge/%F3%A0%80%A0-Support%20us-blueviolet.svg?logo=cash-app&logoColor=white&logoWidth=15'
    alt: 'Become a FreeSewing Patron'
  instagram:
    link: 'https://instagram.com/freesewing_org'
    img: 'https://img.shields.io/badge/%F3%A0%80%A0-Follow%20us-E4405F.svg?logo=instagram&logoColor=white&logoWidth=15'
    alt: 'Follow @freesewing_org on Twitter'
