Unreleased:
  date:
  Added:
    i18n:
      - Added translations for Penelope, Waralee, and Simone
    simone:
      - Added the Simone shirt pattern
    penelope:
      - Added the Penelope Pencil Skirt pattern by @woutervdub
    utils:
      - Added backend methods for administration
    waralee:
      - Added the Waralee wrap Pants pattern by @woutervdub
  Changed:
    core:
      - The pattern super constructor now sets a `config` property that
        holds the pattern configuration. This means that unlike before, there
        is no need to instantiate a pattern to access its config. You can just
        import the pattern, and it's config property will contain the pattern config.
    components:
      - Added Penelope and Waralee linedrawings
    simon:
      - "[#123](https://github.com/freesewing/freesewing/issues/123):
        Added a box pleat option to Simon"
      - Added the `backDarts` option to control the inclusion of back darts
      - Added the `backDartsShaping` option to control the amount of shaping by the back darts

  Deprecated:
    patterns:
      - The [@freesewing/patterns](https://www.npmjs.com/package/@freesewing/patterns)
        package has been deprecated. Please import our patterns individually.
  Removed:
  Fixed:
    components:
      - Fixed display of nested option in SampleConfigurator
    simon:
      - Fixed an issue where the store wasn't properly initialized causing hips and waist ease
        to be set incorrectly
      - Added a missing paperless dimension for the waist
  Security:

2.0.4:
  date: 2019-09-27
  Added:
    components:
      - Advanced options and settings are now hidden by default in DraftConfigurator
  Fixed:
    carlton:
      - "[#108](https://github.com/freesewing/freesewing/issues/108):
        Fixed incorrect width of the Carlton tail"
    components:
      - "[#104](https://github.com/freesewing/freesewing/issues/104):
        Fixed incorrect embed setting on Workbench pattern export"

2.0.3:
  date: 2019-09-15
  Changed:
    components:
      - Tweaked DraftConfigurator tags to match CSS rules after frontend upgrade to react-intl v3
  Fixed:
    bruce:
      - "[#106](https://github.com/freesewing/freesewing/issues/106):
        Fix incorrect hem allowance"
    create-freesewing-pattern:
      - Updated example package.json to use latest tag rather than beta
    utils:
      - Fix measurementDiffers to pass breasts parameter to necstimate

2.0.2:
  date: 2019-09-06
  Added:
    i18n:
      - "[#90](https://github.com/freesewing/freesewing/issues/90):
        Added missing option translations for Benjamin, Florent, Sandy, Shin, and Theo"
  Changed:
    create-freesewing-pattern:
      - Updated dependencies
  Fixed:
    benjamin:
      - Added bandLength option to fit optiongroup (it was missing)
    css-theme:
      - Updated styles for DraftConfigurator component for pattern options 3 levels deep
    components:
      - "[#104](https://github.com/freesewing/freesewing.org/issues/104):
        Changed `onDragEnd` to `onChangeCommitted` in slider element
        (change in material-ui API when slider came out of beta)"
      - Workbench now also lets you preload a `withBreasts` set of measurements
      - DraftConfigurator now properly styles pattern options 3 levels deep
      - "[#105](https://github.com/freesewing/freesewing.org/issues/105):
        Moved state change in render loop to useEffect"
    create-freesewing-pattern:
      - Added missing `file-saver` dependency
    jaeger:
      - "[#76](https://github.com/freesewing/freesewing.org/issues/76):
        Fixed a typo in Jaeger that was causing the side vent length to be wrong"
    simon:
      - "[#100](https://github.com/freesewing/freesewing.org/issues/100):
        Updated simon with more sensible defaults for ease options"
      - "[#102](https://github.com/freesewing/freesewing.org/issues/102):
        Fixed 'Snippets not defined' error when drafting a seperate button placket"
      - "[#103](https://github.com/freesewing/freesewing.org/issues/103):
        Fixed 'hemSa not defined' when drafting paperless Simon without seam allowance"
    utils:
      - Removed lingering debug statement in formatImperial

2.0.1:
  date: 2019-09-01
  Added:
    utils:
      - The `measurementDiffers` method is new.
    models:
      - Expanded the size ranges available.
      - Added the `withBreasts` models which were missing in earlier releases.
  Changed:
    models:
      - The models data is now based on the data from the `neckstimate` method in the utils package.
  Fixed:
    theo:
      - "[#78](https://github.com/freesewing/freesewing/issues/78):
        Removed inherited notches from fly shield and side piece."
    models:
      - "[#86](https://github.com/freesewing/freesewing/issues/86):
        The `seatCircumference` measurement was missing, thus making it unavailable on the website"

