aaron: 'A FreeSewing pattern for a A-shirt or tank top'
benjamin: 'A FreeSewing pattern for a bow tie'
bent: 'A FreeSewing pattern for a menswear body block with a two-part sleeve'
breanna: 'A FreeSewing pattern for a basic body block for womenswear'
brian: 'A FreeSewing pattern for a basic body block for menswear'
bruce: 'A FreeSewing pattern for boxer briefs'
carlita: 'A FreeSewing pattern for Sherlock Holmes cosplay; Or just a nice long coat'
carlton: 'A FreeSewing pattern for Sherlock Holmes cosplay; Or just a nice long coat'
cathrin: 'A FreeSewing pattern for a underbust corset / waist trainer'
components: 'A collection of React components for FreeSewing web UIs'
core: 'A library for creating made-to-measure sewing patterns'
create-freesewing-pattern: 'Initializer package for FreeSewing patterns: npm init FreeSewing-pattern'
css-theme: 'A CSS theme for FreeSewing web UIs'
diana: 'A FreeSewing pattern for a top with a draped neck'
examples: 'A FreeSewing pattern holding examples for our documentation'
florent: 'A FreeSewing pattern for a flat cap'
florence: 'A FreeSewing pattern for a face mask'
gatsby-remark-jargon: 'A gatsby-transformer-remark sub-plugin for jargon terms'
holmes: 'A FreeSewing pattern for a Sherlock Holmes hat'
huey: 'A FreeSewing pattern for a zip-up hoodie'
hugo: 'A FreeSewing pattern for a hooded jumper with raglan sleeves'
i18n: 'Translations for the FreeSewing project'
jaeger: 'A FreeSewing pattern for a sport coat style jacket'
models: 'Body measurements data for a range of default sizes'
mui-theme: 'A Material-UI theme for FreeSewing web UIs'
pattern-info: 'Information about available freesewing patterns'
penelope: 'A FreeSewing pattern for a pencil skirt'
plugin-banner: 'A FreeSewing plugin to repeat text on a path'
plugin-bundle: 'An umbrella package of 8 essential FreeSewing build-time plugins'
plugin-bust: 'A FreeSewing plugin that helps with bust-adjusting menswear patterns'
plugin-buttons: 'A FreeSewing plugin that provides button and buttonhole snippets'
plugin-cutonfold: 'A FreeSewing plugin to add cut-on-fold indicators on your patterns'
plugin-debug: 'A FreeSewing plugin to log debug info to your browser console'
plugin-designer: 'A FreeSewing plugin to facilitate pattern design'
plugin-dimension: 'A FreeSewing plugin to add dimensions to your (paperless) pattern'
plugin-export-dxf: 'A FreeSewing plugin to export your pattern as DXF-ASTM'
plugin-flip: 'A FreeSewing plugin to flip parts horizontally'
plugin-gore: 'A FreeSewing plugin to generate gores for a semi-sphere or dome'
plugin-grainline: 'A FreeSewing plugin to add grainline indicators on your patterns'
plugin-i18n: 'A FreeSewing plugin for pattern translation'
plugin-logo: 'A FreeSewing plugin to add our logo to your patterns'
plugin-round: 'A FreeSewing plugin to round corners'
plugin-scalebox: 'A FreeSewing plugin to add a scalebox to your pattern'
plugin-sprinkle: 'A FreeSewing plugin to bulk-add snippets to your pattern'
plugin-svgattr: 'A FreeSewing plugin to set SVG attributes'
plugin-theme: 'A FreeSewing plugin that provides a default theme'
plugin-title: 'A FreeSewing plugin to add a title to your pattern parts'
plugin-validate: 'A FreeSewing plugin that validates aspects of your code'
prettier-config: "FreeSewing's shared configuration for prettier"
remark-jargon: 'A Remark plugin for jargon terms'
rendertest: 'A FreeSewing pattern to test (y)our render engine our CSS'
sandy: 'A FreeSewing pattern for a circle skirt'
shin: 'A FreeSewing pattern for swim trunks'
simon: 'A FreeSewing pattern for a button down shirt'
simone: 'A FreeSewing pattern for a button down shirt (Simone = Simon for people with breasts)'
sven: 'A FreeSewing pattern for a straightforward sweater'
tamiko: 'A FreeSewing pattern for a zero-waste top'
theo: 'A FreeSewing pattern for classic trousers'
titan: 'A FreeSewing block for trousers'
trayvon: 'A FreeSewing pattern for a tie'
tutorial: "A FreeSewing pattern for a baby bib that's used in our tutorial"
utils: 'A collection of utilities shared across freesewing frontend projects'
wahid: 'A FreeSewing pattern for a classic fitted waistcoat'
waralee: 'A FreeSewing pattern for wrap pants'
