noNamespace:
  - create-freesewing-pattern
  - remark-jargon
  - gatsby-remark-jargon
customRollup:
  - components
  - core
  - css-theme
  - gatsby-remark-jargon
  - i18n
  - plugin-theme
  - remark-jargon
  - utils
  - prettier-config
packageJson:
  components:
    # react-scripts doesn't handle .mjs files correctly
    module: '!'
    files:
      - "Blockquote/*"
      - "Draft/*"
      - "DraftConfigurator/*"
      - "Emblem/*"
      - "Example/*"
      - "Footer/*"
      - "Icon/*"
      - "LineDrawing/*"
      - "Logo/*"
      - "Navbar/*"
      - "Ogol/*"
      - "Robot/*"
      - "SampleConfigurator/*"
      - "Spinner/*"
      - "withGist/*"
      - "withLanguage/*"
      - "withStorage/*"
      - "Workbench/*"
  create-freesewing-pattern:
    bin:
      create-freesewing-pattern: index.js
    main: index.js
    module: '!'
    files:
      - lib
      - template
      - README.md
      - package.json
      - '!lib/*.test.js'
      - '!template/default/node_modules'
  css-theme:
    main: dist/theme.css
    module: '!'
  i18n:
    # react-scripts doesn't handle .mjs files correctly
    module: '!'
  prettier-config:
    main: "index.json"
    module: '!'
    scripts: { build: "echo \"prettier-config: No build required\" && exit 0" }
    keywords:
      - prettier
    files:
      - index.json
      - package.json
  utils:
    # react-scripts doesn't handle .mjs files correctly
    module: '!'
    files:
      - "backend/*"
      - "camelCase/*"
      - "capitalize/*"
      - "cloneObject/*"
      - "defaultGist/*"
      - "defaultSa/*"
      - "formatImperial/*"
      - "formatMm/*"
      - "measurementAsMm/*"
      - "measurementDiffers/*"
      - "neckstimate/*"
      - "optionDefault/*"
      - "optionType/*"
      - "roundMm/*"
      - "roundMmDown/*"
      - "roundMmUp/*"
      - "sliderStep/*"
      - "smallestImperialStep/*"
      - "storage/*"
      - "tiler/*"
      - "validateEmail/*"
      - "validateTld/*"

