noNamespace:
  - rehype-jargon
  - rehype-highlight-lines
customBuild:
  - i18n
  - new-design
  - prettier-config
  - plugin-bundle
  - rehype-jargon
  - rehype-highlight-lines
skipTests:
  - theo
packageJson:
  backend:
    name: backend.freesewing.org
  bee:
    author: bobgeorgethe3rd (https://github.com/bobgeorgethe3rd)
  benjamin:
    author: woutervdub (https://github.com/woutervdub)
  code:
    c8:
      reporter: html
      all: yes
      extension: mjs
      exclude:
        - 'node_modules/*'
        - 'tests'
  hi:
    author: woutervdub (https://github.com/woutervdub)
  holmes:
    author: AlfaLyr (https://github.com/alfalyr)
  i18n:
    private: true
  lucy:
    author: SeaZeeZee (https://github.com/SeaZeeZee)
  lunetius: &starf
    author: Starfetch (https://github.com/starfetch)
  magde:
    author: clegganator259 (https://github.com/clegganator259)
  new-design:
    exports: '!'
    bin:
      new-design: './index.mjs'
    files:
      - README.md
      - package.json
      - lib/**/*
      - shared/**/*
      - templates/**/*
      - index.mjs
      - package.json
      - data.mjs
    module: '!'
  noble:
    author: woutervdub (https://github.com/woutervdub)
  octoplushy:
    author: woutervdub (https://github.com/woutervdub)
  plugin-gore:
    author: AlfaLyr (https://github.com/alfalyr)
  prettier-config:
    type: 'module'
    exports: { .: './index.json' }
    scripts: { build: 'echo "prettier-config: No build required" && exit 0' }
    keywords:
      - prettier
    files:
      - index.json
      - package.json
  rehype-hightlight-lines:
    private: true
  sandy:
    author: AlfaLyr (https://github.com/alfalyr)
  tiberius: *starf
  unice:
    author: Anna Puk (https://github.com/anna-puk)
  ursula:
    author: Natalia Sayang (https://github.com/nataliasayang)
  waralee:
    author: woutervdub (https://github.com/woutervdub)
  walburga: *starf
  yuri:
    author: biou (https://github.com/biou)
