noNamespace:
  - create-freesewing-pattern
  - remark-jargon
  - gatsby-remark-jargon
customRollup:
  - components
  - core
  - css-theme
  - gatsby-remark-jargon
  - i18n
  - remark-jargon
  - utils
  - prettier-config
  - strapi
  - freesewing.dev
  - freesewing.org
namedExports:
  - css-theme
  - models
  - pattern-info
  - mui-theme
packageJson:
  benjamin:
    author: woutervdub (https://github.com/woutervdub)
  components:
    # react-scripts doesn't handle .mjs files correctly
    module: '!'
    files:
      - 'Blockquote/*'
      - 'Draft/*'
      - 'DraftConfigurator/*'
      - 'Emblem/*'
      - 'Example/*'
      - 'Footer/*'
      - 'Icon/*'
      - 'Legend/*'
      - 'LineDrawing/*'
      - 'Logo/*'
      - 'Navbar/*'
      - 'Ogol/*'
      - 'Robot/*'
      - 'SampleConfigurator/*'
      - 'Spinner/*'
      - 'withGist/*'
      - 'withLanguage/*'
      - 'withStorage/*'
      - 'Workbench/*'
  create-freesewing-pattern:
    bin:
      create-freesewing-pattern: index.js
    main: index.js
    module: '!'
    files:
      - lib
      - template
      - README.md
      - package.json
      - '!lib/*.test.js'
      - '!template/default/node_modules'
  css-theme:
    main: dist/theme.css
    module: '!'
  freesewing.dev:
    private: true
  freesewing.org:
    private: true
  holmes:
    author: AlfaLyr (https://github.com/alfalyr)
  i18n:
    # react-scripts doesn't handle .mjs files correctly
    module: '!'
  gatsby-remark-jargon:
    keywords:
      - remark
      - mdx
      - jargon
      - gatsby
      - gatsby-plugin
  plugin-gore:
    author: AlfaLyr (https://github.com/alfalyr)
  prettier-config:
    main: 'index.json'
    module: '!'
    scripts: { build: 'echo "prettier-config: No build required" && exit 0' }
    keywords:
      - prettier
    files:
      - index.json
      - package.json
  sandy:
    author: AlfaLyr (https://github.com/alfalyr)
  strapi:
    private: true
    scripts:
      develop: strapi develop
      start: strapi start
      build: strapi build
      strapi: strapi
    homepage: "https://posts.freesewing.org/"
    files: []
    publishConfig: {}
    rollup: {}
  utils:
    # react-scripts doesn't handle .mjs files correctly
    module: '!'
    files:
      - 'backend/*'
      - 'camelCase/*'
      - 'capitalize/*'
      - 'cloneObject/*'
      - 'convertSize/*'
      - 'defaultGist/*'
      - 'defaultSa/*'
      - 'formatImperial/*'
      - 'formatMm/*'
      - 'isDegMeasurement/*'
      - 'measurementAsMm/*'
      - 'measurementDiffers/*'
      - 'neckstimate/*'
      - 'optionDefault/*'
      - 'optionType/*'
      - 'roundMm/*'
      - 'roundMmDown/*'
      - 'roundMmUp/*'
      - 'sliderStep/*'
      - 'smallestImperialStep/*'
      - 'storage/*'
      - 'tiler/*'
      - 'validateEmail/*'
      - 'validateTld/*'
  waralee:
    author: woutervdub (https://github.com/woutervdub)
