name: Unit tests - Plugin-mirror

on:
  push:
    branches:
      - develop
    paths:
      - 'packages/plugin-mirror/**'
      - '!packages/plugin-mirror/README.md'
  pull_request:
    branches:
      - develop
    paths:
      - 'packages/plugin-mirror/**'
      - '!packages/plugin-mirror/README.md'

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: cd packages/plugin-mirror && npm install
        env:
          CI: true
      - name: Install peer & test dependencies in monorepo root
        run: "npm install @freesewing/core@^2.20.6 mocha@^9.1.1 chai@^4.2.0 @babel/core@^7.11.0 @babel/register@^7.10.5 rollup@^2.50.6 @rollup/plugin-babel@^5.3.0 @rollup/plugin-commonjs@^21.0.1 @rollup/plugin-json@^4.1.0 @rollup/plugin-node-resolve@^13.0.0 rollup-plugin-peer-deps-external@^2.2.4"
        env:
          CI: true
      - name: Install peer & test dependencies
        run: "cd packages/plugin-mirror && npm install @freesewing/core@^2.20.6 mocha@^9.1.1 chai@^4.2.0 @babel/core@^7.11.0 @babel/register@^7.10.5 rollup@^2.50.6 @rollup/plugin-babel@^5.3.0 @rollup/plugin-commonjs@^21.0.1 @rollup/plugin-json@^4.1.0 @rollup/plugin-node-resolve@^13.0.0 rollup-plugin-peer-deps-external@^2.2.4"
        env:
          CI: true
      - name: Build plugin
        run: cd packages/plugin-mirror && npm run build
      - name: Run plugin unit tests
        run: cd packages/plugin-mirror && npm run testci
